#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v5
# autospec commit: c02b2fe
#
Name     : thermal_daemon
Version  : 2.5.7
Release  : 57
URL      : https://github.com/intel/thermal_daemon/archive/v2.5.7/thermal_daemon-2.5.7.tar.gz
Source0  : https://github.com/intel/thermal_daemon/archive/v2.5.7/thermal_daemon-2.5.7.tar.gz
Summary  : The "Linux Thermal Daemon" program from 01.org
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ GPL-3.0
Requires: thermal_daemon-autostart = %{version}-%{release}
Requires: thermal_daemon-bin = %{version}-%{release}
Requires: thermal_daemon-config = %{version}-%{release}
Requires: thermal_daemon-data = %{version}-%{release}
Requires: thermal_daemon-license = %{version}-%{release}
Requires: thermal_daemon-man = %{version}-%{release}
Requires: thermal_daemon-services = %{version}-%{release}
BuildRequires : autoconf-archive
BuildRequires : autoconf-archive-dev
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(libevdev)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(upower-glib)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Add-add-udev-rule-to-start-thermald-just-when-the-ba.patch
Patch2: 0002-Add-thermal-conf-example-for-KBL-NUC.patch

%description
Thermal Daemon monitors and controls platform temperature.

%package autostart
Summary: autostart components for the thermal_daemon package.
Group: Default

%description autostart
autostart components for the thermal_daemon package.


%package bin
Summary: bin components for the thermal_daemon package.
Group: Binaries
Requires: thermal_daemon-data = %{version}-%{release}
Requires: thermal_daemon-config = %{version}-%{release}
Requires: thermal_daemon-license = %{version}-%{release}
Requires: thermal_daemon-services = %{version}-%{release}

%description bin
bin components for the thermal_daemon package.


%package config
Summary: config components for the thermal_daemon package.
Group: Default

%description config
config components for the thermal_daemon package.


%package data
Summary: data components for the thermal_daemon package.
Group: Data

%description data
data components for the thermal_daemon package.


%package license
Summary: license components for the thermal_daemon package.
Group: Default

%description license
license components for the thermal_daemon package.


%package man
Summary: man components for the thermal_daemon package.
Group: Default

%description man
man components for the thermal_daemon package.


%package services
Summary: services components for the thermal_daemon package.
Group: Systemd services
Requires: systemd

%description services
services components for the thermal_daemon package.


%prep
%setup -q -n thermal_daemon-2.5.7
cd %{_builddir}/thermal_daemon-2.5.7
%patch -P 1 -p1
%patch -P 2 -p1
pushd ..
cp -a thermal_daemon-2.5.7 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711750587
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%autogen --disable-static --sysconfdir=/usr/share
make  %{?_smp_mflags}

pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%autogen --disable-static --sysconfdir=/usr/share
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1711750587
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/thermal_daemon
cp %{_builddir}/thermal_daemon-%{version}/COPYING %{buildroot}/usr/share/package-licenses/thermal_daemon/b3aebbdebf056cbf1cb73b76edf8ea105c37239d || :
cp %{_builddir}/thermal_daemon-%{version}/tools/thermal_monitor/COPYING %{buildroot}/usr/share/package-licenses/thermal_daemon/31a3d460bb3c7d98845187c716a30db81c44b615 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
## install_append content
mkdir -p %{buildroot}/usr/share/dbus-1/system.d
install -p -D -m 644 data/org.freedesktop.thermald.conf %{buildroot}/usr/share/dbus-1/system.d/org.freedesktop.thermald.conf

mkdir -p %{buildroot}/usr/lib/udev/rules.d/
install -p -D -m 644 90-thermald-on-battery.rules %{buildroot}/usr/lib/udev/rules.d/90-thermald-on-battery.rules

mkdir -p %{buildroot}/usr/share/thermald/
install -p -D -m 644 thermal-conf.KBL_NUC.xml %{buildroot}/usr/share/thermald/thermal-conf.KBL_NUC.xml

mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
ln -s ../thermald.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/thermald.service

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/thermald
/usr/bin/thermald

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/90-thermald-on-battery.rules

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/system-services/org.freedesktop.thermald.service
/usr/share/dbus-1/system.d/org.freedesktop.thermald.conf
/usr/share/thermald/thermal-conf.KBL_NUC.xml
/usr/share/thermald/thermal-cpu-cdev-order.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/thermal_daemon/31a3d460bb3c7d98845187c716a30db81c44b615
/usr/share/package-licenses/thermal_daemon/b3aebbdebf056cbf1cb73b76edf8ea105c37239d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/thermal-conf.xml.5
/usr/share/man/man8/thermald.8

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/thermald.service
/usr/lib/systemd/system/thermald.service
